/**
 * @license
 * Copyright 2026 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.POM({
  name: 'knowledge',
  help: `Pre-canned vector embeddings journal for the RAG knowledge base.

  WARNING: vectorEmbeddings.jrl is ~6.6 MB of pre-computed embeddings and will
  go stale as documents are added or updated. Long-term, this file should be
  generated by a build step (e.g. an indexing task that embeds all source flows
  at build time) rather than committed as static data.`
});
