/**
 * @license
 * Copyright 2026 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.CLASS({
  package: 'foam.core.job',
  name: 'Job',
  abstract: true,

  implements: [
    'foam.lang.ContextAgent',
    'foam.core.auth.Authorizable',
    'foam.core.auth.CreatedAware',
    'foam.core.auth.CreatedByAware'
  ],

  documentation: `Base class for a long-running task executed on the server.

    Submit a Job to the jobDAO and the put returns as soon as the row is
    written, carrying the generated UUID. A Rule hands the Job to the
    threadPool wrapped in a JobRunner, which owns the status transitions, so an
    implementation only has to supply execute(). The submitter polls
    jobDAO.find(id) to watch it run; nothing about this needs a new endpoint.

    This exists because a task submitted synchronously through DAO.cmd() is
    bounded by the gateway's request timeout, and the work does not care about
    that limit.

    A Job that can say how far along it is calls reportProgress() as it goes.
    One that cannot leaves progress at -1, which reads as "unknown", not "0%".

    Job is the jobDAO's 'of', so every storable Job extends it: an MDAO indexes
    through its 'of' id PropertyInfo, which casts, and an interface generates no
    ClassInfo to index by.`,

  javaImports: [
    'foam.dao.DAO',
    'foam.lang.X',
    'foam.core.auth.AuthService',
    'foam.core.auth.AuthorizationException',
    'foam.core.auth.CreatedByAware',
    'foam.core.auth.Subject'
  ],

  tableColumns: [
    'id',
    'status',
    'progress',
    'statusMsg',
    'created',
    'createdBy',
    'executionTime'
  ],

  properties: [
    {
      documentation: 'UUID, generated by the jobDAO on put. The handle the submitter polls with.',
      class: 'String',
      name: 'id',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      class: 'Enum',
      of: 'foam.core.job.JobStatus',
      name: 'status',
      value: 'SCHEDULED',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      documentation: 'Human readable detail of what the Job is doing right now.',
      class: 'String',
      name: 'statusMsg',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      documentation: `Completion percentage, or -1 when the Job cannot determine
        its own. Optional: only a Job that calls reportProgress() moves it.`,
      class: 'Int',
      name: 'progress',
      value: -1,
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      documentation: 'Stack trace of the Throwable that failed the Job. Only set on FAILED.',
      class: 'String',
      name: 'exception',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO',
      view: {
        class: 'foam.u2.view.ModeAltView',
        readView: { class: 'foam.u2.view.PreView' }
      }
    },
    {
      documentation: 'Wall-clock run time, set when the Job stops, whether it completed or failed.',
      class: 'Duration',
      name: 'executionTime',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    }
  ],

  methods: [
    {
      name: 'save',
      documentation: `Write this Job's current state back to the jobDAO so a
        poller can see it. The jobDAO clones on put, so this instance stays
        mutable and can be saved again as the Job advances.`,
      args: 'X x',
      javaCode: `
        ((DAO) x.get("jobDAO")).inX(x).put(this);
      `
    },
    {
      name: 'reportProgress',
      documentation: 'Record how far along this Job is and publish it to the jobDAO.',
      args: 'X x, String statusMsg, int progress',
      javaCode: `
        setStatusMsg(statusMsg);
        setProgress(progress);
        save(x);
      `
    },
    {
      documentation: `createdBy is stamped by CreatedByAwareDAO, which sits
        inside AuthorizationDAO, so it is still unset here. Submitting is
        governed by access to the jobDAO service itself.`,
      name: 'authorizeOnCreate',
      javaCode: `
        // not authorized here, see documentation
      `
    },
    {
      name: 'authorizeOnRead',
      javaCode: `
        isOwnerOrHasPermission(x, this, "read");
      `
    },
    {
      name: 'authorizeOnUpdate',
      javaCode: `
        isOwnerOrHasPermission(x, oldObj, "update");
      `
    },
    {
      name: 'authorizeOnDelete',
      javaCode: `
        isOwnerOrHasPermission(x, this, "remove");
      `
    },
    {
      name: 'isOwnerOrHasPermission',
      documentation: `A user may read, update or delete a Job they submitted.
        Anyone holding job.[operation].* may do so to any Job, which is how the
        system user runs the retention sweep.`,
      args: 'Context x, FObject obj, String action',
      javaThrows: [ 'foam.core.auth.AuthorizationException' ],
      javaCode: `
        Subject subject = (Subject) x.get("subject");
        if ( subject.getUser().getId() == ((CreatedByAware) obj).getCreatedBy() &&
             subject.getRealUser().getId() == ((CreatedByAware) obj).getCreatedByAgent() )
          return;

        AuthService auth = (AuthService) x.get("auth");
        if ( auth.check(x, "job." + action + ".*") ) return;

        throw new AuthorizationException("You do not have permission to " + action + " this Job");
      `
    }
  ]
});
