foam.POM({
  name: 'console',
  files: [
    { name: '../../u2/mlang/Table',    flags: 'js|java' },
    { name: 'AbstractDAOAgent',        flags: 'js' },
    { name: 'CellsSink',               flags: 'js|java' },
    { name: 'Check',                   flags: 'js' },
    { name: 'CitationSink',            flags: 'js|java' },
    { name: 'Console',                 flags: 'js' },
    { name: 'ConsoleZACClient',        flags: 'js' },
    { name: 'DAOCreate',               flags: 'js' },
    { name: 'DAOPrompt',               flags: 'js' },
    { name: 'Doc',                     flags: 'js' },
    { name: 'DocumentReadWriteView',   flags: 'js' },
    { name: 'DuplicateSink',           flags: 'js|java' },
    { name: 'EditSink',                flags: 'js|java' },
    { name: 'FlowAccess',              flags: 'js|java' },
    { name: 'RoleFlowAccess',          flags: 'js|java' },
    { name: 'UserFlowAccess',          flags: 'js|java' },
    { name: 'Flow',                    flags: 'js|java' },
    { name: 'GridBy',                  flags: 'js|java' },
    { name: 'GridByView',              flags: 'js' },
    { name: 'Header',                  flags: 'js' },
    { name: 'JSONSink',                flags: 'js|java' },
    { name: 'SinkAgent',               flags: 'js|java' },
    { name: 'CommandItemView',         flags: 'js' },
    { name: 'ReflowToolBar',           flags: 'js' },
    { name: 'ModelDAO',                flags: 'js' },
    { name: 'PropertyChoiceView',      flags: 'js' },
    { name: 'ComparatorView',          flags: 'js' },
    { name: 'PredicateView',           flags: 'js' },
    { name: 'PropertyListView',        flags: 'js' },
    { name: 'PropertyOrderChoiceView', flags: 'js' },
    { name: 'ReactiveDetailView',      flags: 'js' },
    { name: 'DynamicReflowData',       flags: 'js' },
    { name: 'DynamicReflowComponents', flags: 'js' },
    { name: 'DynamicReflowHelp',       flags: 'js' },
    { name: 'Script',                  flags: 'js' },
    { name: 'Signature',               flags: 'js' },
    { name: 'SinkView',                flags: 'js' },
    { name: 'CopyFromBorder',          flags: 'js' },
    { name: 'Upload',                  flags: 'js' },
    { name: 'UploadAgent',             flags: 'js|java' },
    { name: 'ViewSink',                flags: 'js|java' },
    { name: 'XHR',                     flags: 'js' },
    { name: 'float/Test',              flags: 'js' },
    { name: 'XMLSink',                 flags: 'js|java' },
    { name: 'cmd/Commands',            flags: 'js|java' },
    { name: 'ColumnParser',            flags: 'js' },
    { name: 'Prompt',                  flags: 'js' },
    { name: 'lib',                     flags: 'js' },
    { name: 'ToolbarControl',          flags: 'js|java' },
    { name: 'control/HelpControl',     flags: 'js' }
  ]
});
